// Generated by jextract

package top.dreamlike.nativeLib.inet;

import top.dreamlike.common.CType;
import top.dreamlike.helper.RuntimeHelper;

import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.MemoryLayout;
import java.lang.invoke.MethodHandle;
class constants$7 {

    static final FunctionDescriptor inet_network$FUNC = FunctionDescriptor.of(CType.C_INT$LAYOUT,
        CType.C_POINTER$LAYOUT
    );
    static final MethodHandle inet_network$MH = RuntimeHelper.downcallHandle(
        "inet_network",
        constants$7.inet_network$FUNC
    );
    static final FunctionDescriptor inet_ntoa$FUNC = FunctionDescriptor.of(CType.C_POINTER$LAYOUT,
        MemoryLayout.structLayout(
            CType.C_INT$LAYOUT.withName("s_addr")
        ).withName("in_addr")
    );
    static final MethodHandle inet_ntoa$MH = RuntimeHelper.downcallHandle(
        "inet_ntoa",
        constants$7.inet_ntoa$FUNC
    );
    static final FunctionDescriptor inet_pton$FUNC = FunctionDescriptor.of(CType.C_INT$LAYOUT,
        CType.C_INT$LAYOUT,
        CType.C_POINTER$LAYOUT,
        CType.C_POINTER$LAYOUT
    );
    static final MethodHandle inet_pton$MH = RuntimeHelper.downcallHandle(
        "inet_pton",
        constants$7.inet_pton$FUNC
    );
    static final FunctionDescriptor inet_ntop$FUNC = FunctionDescriptor.of(CType.C_POINTER$LAYOUT,
        CType.C_INT$LAYOUT,
        CType.C_POINTER$LAYOUT,
        CType.C_POINTER$LAYOUT,
        CType.C_INT$LAYOUT
    );
    static final MethodHandle inet_ntop$MH = RuntimeHelper.downcallHandle(
        "inet_ntop",
        constants$7.inet_ntop$FUNC
    );
    static final FunctionDescriptor inet_aton$FUNC = FunctionDescriptor.of(CType.C_INT$LAYOUT,
        CType.C_POINTER$LAYOUT,
        CType.C_POINTER$LAYOUT
    );
    static final MethodHandle inet_aton$MH = RuntimeHelper.downcallHandle(
        "inet_aton",
        constants$7.inet_aton$FUNC
    );
    static final FunctionDescriptor inet_neta$FUNC = FunctionDescriptor.of(CType.C_POINTER$LAYOUT,
        CType.C_INT$LAYOUT,
        CType.C_POINTER$LAYOUT,
        CType.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle inet_neta$MH = RuntimeHelper.downcallHandle(
        "inet_neta",
        constants$7.inet_neta$FUNC
    );
}


