// Generated by jextract

package top.dreamlike.nativeLib.liburing;

import java.lang.foreign.*;

public interface __sighandler_t {

    void apply(int _x0);
    static MemorySegment allocate(__sighandler_t fi, MemorySession session) {
        return RuntimeHelper.upcallStub(__sighandler_t.class, fi, constants$6.__sighandler_t$FUNC, session);
    }
    static __sighandler_t ofAddress(MemoryAddress addr, MemorySession session) {
        MemorySegment symbol = MemorySegment.ofAddress(addr, 0, session);
        return (int __x0) -> {
            try {
                constants$6.__sighandler_t$MH.invokeExact((Addressable)symbol, __x0);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


