// Generated by jextract

package top.dreamlike.nativeLib.liburing;

import java.lang.foreign.*;

public class atomic_flag {

    static final  GroupLayout $struct$LAYOUT = MemoryLayout.structLayout(

    ).withName("atomic_flag");
    public static MemoryLayout $LAYOUT() {
        return atomic_flag.$struct$LAYOUT;
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }

    public static MemorySegment ofAddress(MemorySegment addr, Arena session) {
        return RuntimeHelper.asArray(addr, $LAYOUT(), 1, session);
    }
}


