// Generated by jextract

package top.dreamlike.nativeLib.liburing;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$17 {

    static final FunctionDescriptor timer_delete$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle timer_delete$MH = RuntimeHelper.downcallHandle(
        "timer_delete",
        constants$17.timer_delete$FUNC
    );
    static final FunctionDescriptor timer_settime$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle timer_settime$MH = RuntimeHelper.downcallHandle(
        "timer_settime",
        constants$17.timer_settime$FUNC
    );
    static final FunctionDescriptor timer_gettime$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle timer_gettime$MH = RuntimeHelper.downcallHandle(
        "timer_gettime",
        constants$17.timer_gettime$FUNC
    );
    static final FunctionDescriptor timer_getoverrun$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle timer_getoverrun$MH = RuntimeHelper.downcallHandle(
        "timer_getoverrun",
        constants$17.timer_getoverrun$FUNC
    );
    static final FunctionDescriptor timespec_get$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle timespec_get$MH = RuntimeHelper.downcallHandle(
        "timespec_get",
        constants$17.timespec_get$FUNC
    );
    static final  OfInt getdate_err$LAYOUT = Constants$root.C_INT$LAYOUT;
    static final VarHandle getdate_err$VH = constants$17.getdate_err$LAYOUT.varHandle();
    static final MemorySegment getdate_err$SEGMENT = RuntimeHelper.lookupGlobalVariable("getdate_err", constants$17.getdate_err$LAYOUT);
}


