// Generated by jextract

package top.dreamlike.nativeLib.liburing;

import java.lang.foreign.*;
import java.lang.invoke.VarHandle;

public class file_dedupe_range {

    static final  GroupLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_LONG_LONG$LAYOUT.withName("src_offset"),
        Constants$root.C_LONG_LONG$LAYOUT.withName("src_length"),
        Constants$root.C_SHORT$LAYOUT.withName("dest_count"),
        Constants$root.C_SHORT$LAYOUT.withName("reserved1"),
        Constants$root.C_INT$LAYOUT.withName("reserved2"),
        MemoryLayout.sequenceLayout(0, MemoryLayout.structLayout(
            Constants$root.C_LONG_LONG$LAYOUT.withName("dest_fd"),
            Constants$root.C_LONG_LONG$LAYOUT.withName("dest_offset"),
            Constants$root.C_LONG_LONG$LAYOUT.withName("bytes_deduped"),
            Constants$root.C_INT$LAYOUT.withName("status"),
            Constants$root.C_INT$LAYOUT.withName("reserved")
        ).withName("file_dedupe_range_info")).withName("info")
    ).withName("file_dedupe_range");
    public static MemoryLayout $LAYOUT() {
        return file_dedupe_range.$struct$LAYOUT;
    }
    static final VarHandle src_offset$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("src_offset"));
    public static VarHandle src_offset$VH() {
        return file_dedupe_range.src_offset$VH;
    }
    public static long src_offset$get(MemorySegment seg) {
        return (long)file_dedupe_range.src_offset$VH.get(seg);
    }
    public static void src_offset$set( MemorySegment seg, long x) {
        file_dedupe_range.src_offset$VH.set(seg, x);
    }
    public static long src_offset$get(MemorySegment seg, long index) {
        return (long)file_dedupe_range.src_offset$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void src_offset$set(MemorySegment seg, long index, long x) {
        file_dedupe_range.src_offset$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle src_length$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("src_length"));
    public static VarHandle src_length$VH() {
        return file_dedupe_range.src_length$VH;
    }
    public static long src_length$get(MemorySegment seg) {
        return (long)file_dedupe_range.src_length$VH.get(seg);
    }
    public static void src_length$set( MemorySegment seg, long x) {
        file_dedupe_range.src_length$VH.set(seg, x);
    }
    public static long src_length$get(MemorySegment seg, long index) {
        return (long)file_dedupe_range.src_length$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void src_length$set(MemorySegment seg, long index, long x) {
        file_dedupe_range.src_length$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle dest_count$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("dest_count"));
    public static VarHandle dest_count$VH() {
        return file_dedupe_range.dest_count$VH;
    }
    public static short dest_count$get(MemorySegment seg) {
        return (short)file_dedupe_range.dest_count$VH.get(seg);
    }
    public static void dest_count$set( MemorySegment seg, short x) {
        file_dedupe_range.dest_count$VH.set(seg, x);
    }
    public static short dest_count$get(MemorySegment seg, long index) {
        return (short)file_dedupe_range.dest_count$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void dest_count$set(MemorySegment seg, long index, short x) {
        file_dedupe_range.dest_count$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle reserved1$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("reserved1"));
    public static VarHandle reserved1$VH() {
        return file_dedupe_range.reserved1$VH;
    }
    public static short reserved1$get(MemorySegment seg) {
        return (short)file_dedupe_range.reserved1$VH.get(seg);
    }
    public static void reserved1$set( MemorySegment seg, short x) {
        file_dedupe_range.reserved1$VH.set(seg, x);
    }
    public static short reserved1$get(MemorySegment seg, long index) {
        return (short)file_dedupe_range.reserved1$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void reserved1$set(MemorySegment seg, long index, short x) {
        file_dedupe_range.reserved1$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle reserved2$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("reserved2"));
    public static VarHandle reserved2$VH() {
        return file_dedupe_range.reserved2$VH;
    }
    public static int reserved2$get(MemorySegment seg) {
        return (int)file_dedupe_range.reserved2$VH.get(seg);
    }
    public static void reserved2$set( MemorySegment seg, int x) {
        file_dedupe_range.reserved2$VH.set(seg, x);
    }
    public static int reserved2$get(MemorySegment seg, long index) {
        return (int)file_dedupe_range.reserved2$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void reserved2$set(MemorySegment seg, long index, int x) {
        file_dedupe_range.reserved2$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }

    public static MemorySegment ofAddress(MemorySegment addr, Arena session) {
        return RuntimeHelper.asArray(addr, $LAYOUT(), 1, session);
    }
}


