// Generated by jextract

package top.dreamlike.nativeLib.liburing;

import java.lang.foreign.*;
import java.lang.invoke.VarHandle;

public class io_uring_restriction {

    static final  GroupLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_SHORT$LAYOUT.withName("opcode"),
        MemoryLayout.unionLayout(
            Constants$root.C_CHAR$LAYOUT.withName("register_op"),
            Constants$root.C_CHAR$LAYOUT.withName("sqe_op"),
            Constants$root.C_CHAR$LAYOUT.withName("sqe_flags")
        ).withName("$anon$0"),
        Constants$root.C_CHAR$LAYOUT.withName("resv"),
        MemoryLayout.sequenceLayout(3, Constants$root.C_INT$LAYOUT).withName("resv2")
    ).withName("io_uring_restriction");
    public static MemoryLayout $LAYOUT() {
        return io_uring_restriction.$struct$LAYOUT;
    }
    static final VarHandle opcode$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("opcode"));
    public static VarHandle opcode$VH() {
        return io_uring_restriction.opcode$VH;
    }
    public static short opcode$get(MemorySegment seg) {
        return (short)io_uring_restriction.opcode$VH.get(seg);
    }
    public static void opcode$set( MemorySegment seg, short x) {
        io_uring_restriction.opcode$VH.set(seg, x);
    }
    public static short opcode$get(MemorySegment seg, long index) {
        return (short)io_uring_restriction.opcode$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void opcode$set(MemorySegment seg, long index, short x) {
        io_uring_restriction.opcode$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle register_op$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("$anon$0"), MemoryLayout.PathElement.groupElement("register_op"));
    public static VarHandle register_op$VH() {
        return io_uring_restriction.register_op$VH;
    }
    public static byte register_op$get(MemorySegment seg) {
        return (byte)io_uring_restriction.register_op$VH.get(seg);
    }
    public static void register_op$set( MemorySegment seg, byte x) {
        io_uring_restriction.register_op$VH.set(seg, x);
    }
    public static byte register_op$get(MemorySegment seg, long index) {
        return (byte)io_uring_restriction.register_op$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void register_op$set(MemorySegment seg, long index, byte x) {
        io_uring_restriction.register_op$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle sqe_op$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("$anon$0"), MemoryLayout.PathElement.groupElement("sqe_op"));
    public static VarHandle sqe_op$VH() {
        return io_uring_restriction.sqe_op$VH;
    }
    public static byte sqe_op$get(MemorySegment seg) {
        return (byte)io_uring_restriction.sqe_op$VH.get(seg);
    }
    public static void sqe_op$set( MemorySegment seg, byte x) {
        io_uring_restriction.sqe_op$VH.set(seg, x);
    }
    public static byte sqe_op$get(MemorySegment seg, long index) {
        return (byte)io_uring_restriction.sqe_op$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void sqe_op$set(MemorySegment seg, long index, byte x) {
        io_uring_restriction.sqe_op$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle sqe_flags$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("$anon$0"), MemoryLayout.PathElement.groupElement("sqe_flags"));
    public static VarHandle sqe_flags$VH() {
        return io_uring_restriction.sqe_flags$VH;
    }
    public static byte sqe_flags$get(MemorySegment seg) {
        return (byte)io_uring_restriction.sqe_flags$VH.get(seg);
    }
    public static void sqe_flags$set( MemorySegment seg, byte x) {
        io_uring_restriction.sqe_flags$VH.set(seg, x);
    }
    public static byte sqe_flags$get(MemorySegment seg, long index) {
        return (byte)io_uring_restriction.sqe_flags$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void sqe_flags$set(MemorySegment seg, long index, byte x) {
        io_uring_restriction.sqe_flags$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle resv$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("resv"));
    public static VarHandle resv$VH() {
        return io_uring_restriction.resv$VH;
    }
    public static byte resv$get(MemorySegment seg) {
        return (byte)io_uring_restriction.resv$VH.get(seg);
    }
    public static void resv$set( MemorySegment seg, byte x) {
        io_uring_restriction.resv$VH.set(seg, x);
    }
    public static byte resv$get(MemorySegment seg, long index) {
        return (byte)io_uring_restriction.resv$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void resv$set(MemorySegment seg, long index, byte x) {
        io_uring_restriction.resv$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static MemorySegment resv2$slice(MemorySegment seg) {
        return seg.asSlice(4, 12);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }

    public static MemorySegment ofAddress(MemorySegment addr, Arena session) {
        return RuntimeHelper.asArray(addr, $LAYOUT(), 1, session);
    }
}


