// Generated by jextract

package top.dreamlike.nativeLib.stdio;

import java.lang.foreign.MemorySegment;

class constants$15 {

    static final MemorySegment P_tmpdir$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("/tmp");
}


