// Generated by jextract

package top.dreamlike.liburing;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$25 {

    static final FunctionDescriptor io_uring_register_buffers$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle io_uring_register_buffers$MH = RuntimeHelper.downcallHandle(
        "io_uring_register_buffers",
        constants$25.io_uring_register_buffers$FUNC
    );
    static final FunctionDescriptor io_uring_unregister_buffers$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle io_uring_unregister_buffers$MH = RuntimeHelper.downcallHandle(
        "io_uring_unregister_buffers",
        constants$25.io_uring_unregister_buffers$FUNC
    );
    static final FunctionDescriptor io_uring_register_files$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle io_uring_register_files$MH = RuntimeHelper.downcallHandle(
        "io_uring_register_files",
        constants$25.io_uring_register_files$FUNC
    );
    static final FunctionDescriptor io_uring_unregister_files$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle io_uring_unregister_files$MH = RuntimeHelper.downcallHandle(
        "io_uring_unregister_files",
        constants$25.io_uring_unregister_files$FUNC
    );
    static final FunctionDescriptor io_uring_register_files_update$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle io_uring_register_files_update$MH = RuntimeHelper.downcallHandle(
        "io_uring_register_files_update",
        constants$25.io_uring_register_files_update$FUNC
    );
    static final FunctionDescriptor io_uring_register_eventfd$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle io_uring_register_eventfd$MH = RuntimeHelper.downcallHandle(
        "io_uring_register_eventfd",
        constants$25.io_uring_register_eventfd$FUNC
    );
}


