// Generated by jextract

package top.dreamlike.liburing;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$20 {

    static final FunctionDescriptor __swab32p$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle __swab32p$MH = RuntimeHelper.downcallHandle(
        "__swab32p",
        constants$20.__swab32p$FUNC
    );
    static final FunctionDescriptor __swab64p$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle __swab64p$MH = RuntimeHelper.downcallHandle(
        "__swab64p",
        constants$20.__swab64p$FUNC
    );
    static final FunctionDescriptor __swahw32p$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle __swahw32p$MH = RuntimeHelper.downcallHandle(
        "__swahw32p",
        constants$20.__swahw32p$FUNC
    );
    static final FunctionDescriptor __swahb32p$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle __swahb32p$MH = RuntimeHelper.downcallHandle(
        "__swahb32p",
        constants$20.__swahb32p$FUNC
    );
    static final FunctionDescriptor __swab16s$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle __swab16s$MH = RuntimeHelper.downcallHandle(
        "__swab16s",
        constants$20.__swab16s$FUNC
    );
    static final FunctionDescriptor __swab32s$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle __swab32s$MH = RuntimeHelper.downcallHandle(
        "__swab32s",
        constants$20.__swab32s$FUNC
    );
}


