// Generated by jextract

package top.dreamlike.liburing;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$35 {

    static final FunctionDescriptor io_uring_sq_space_left$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle io_uring_sq_space_left$MH = RuntimeHelper.downcallHandle(
        "io_uring_sq_space_left",
        constants$35.io_uring_sq_space_left$FUNC
    );
    static final FunctionDescriptor io_uring_sqring_wait$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle io_uring_sqring_wait$MH = RuntimeHelper.downcallHandle(
        "io_uring_sqring_wait",
        constants$35.io_uring_sqring_wait$FUNC
    );
    static final FunctionDescriptor io_uring_cq_ready$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle io_uring_cq_ready$MH = RuntimeHelper.downcallHandle(
        "io_uring_cq_ready",
        constants$35.io_uring_cq_ready$FUNC
    );
    static final FunctionDescriptor io_uring_cq_eventfd_enabled$FUNC = FunctionDescriptor.of(Constants$root.C_BOOL$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle io_uring_cq_eventfd_enabled$MH = RuntimeHelper.downcallHandle(
        "io_uring_cq_eventfd_enabled",
        constants$35.io_uring_cq_eventfd_enabled$FUNC
    );
    static final FunctionDescriptor io_uring_cq_eventfd_toggle$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_BOOL$LAYOUT
    );
    static final MethodHandle io_uring_cq_eventfd_toggle$MH = RuntimeHelper.downcallHandle(
        "io_uring_cq_eventfd_toggle",
        constants$35.io_uring_cq_eventfd_toggle$FUNC
    );
    static final FunctionDescriptor io_uring_wait_cqe_nr$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle io_uring_wait_cqe_nr$MH = RuntimeHelper.downcallHandle(
        "io_uring_wait_cqe_nr",
        constants$35.io_uring_wait_cqe_nr$FUNC
    );
}


