// Generated by jextract

package top.dreamlike.liburing;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$32 {

    static final FunctionDescriptor io_uring_prep_openat$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle io_uring_prep_openat$MH = RuntimeHelper.downcallHandle(
        "io_uring_prep_openat",
        constants$32.io_uring_prep_openat$FUNC
    );
    static final FunctionDescriptor io_uring_prep_close$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle io_uring_prep_close$MH = RuntimeHelper.downcallHandle(
        "io_uring_prep_close",
        constants$32.io_uring_prep_close$FUNC
    );
    static final FunctionDescriptor io_uring_prep_read$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle io_uring_prep_read$MH = RuntimeHelper.downcallHandle(
        "io_uring_prep_read",
        constants$32.io_uring_prep_read$FUNC
    );
    static final FunctionDescriptor io_uring_prep_write$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle io_uring_prep_write$MH = RuntimeHelper.downcallHandle(
        "io_uring_prep_write",
        constants$32.io_uring_prep_write$FUNC
    );
    static final FunctionDescriptor io_uring_prep_statx$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle io_uring_prep_statx$MH = RuntimeHelper.downcallHandle(
        "io_uring_prep_statx",
        constants$32.io_uring_prep_statx$FUNC
    );
    static final FunctionDescriptor io_uring_prep_fadvise$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle io_uring_prep_fadvise$MH = RuntimeHelper.downcallHandle(
        "io_uring_prep_fadvise",
        constants$32.io_uring_prep_fadvise$FUNC
    );
}


