// Generated by jextract

package top.dreamlike.liburing;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$22 {

    static final FunctionDescriptor io_uring_register_files_update$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle io_uring_register_files_update$MH = RuntimeHelper.downcallHandle(
        "io_uring_register_files_update",
        constants$22.io_uring_register_files_update$FUNC
    );
    static final FunctionDescriptor io_uring_register_eventfd$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle io_uring_register_eventfd$MH = RuntimeHelper.downcallHandle(
        "io_uring_register_eventfd",
        constants$22.io_uring_register_eventfd$FUNC
    );
    static final FunctionDescriptor io_uring_unregister_eventfd$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle io_uring_unregister_eventfd$MH = RuntimeHelper.downcallHandle(
        "io_uring_unregister_eventfd",
        constants$22.io_uring_unregister_eventfd$FUNC
    );
    static final FunctionDescriptor __io_uring_get_cqe$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle __io_uring_get_cqe$MH = RuntimeHelper.downcallHandle(
        "__io_uring_get_cqe",
        constants$22.__io_uring_get_cqe$FUNC
    );
    static final FunctionDescriptor io_uring_cq_advance$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle io_uring_cq_advance$MH = RuntimeHelper.downcallHandle(
        "io_uring_cq_advance",
        constants$22.io_uring_cq_advance$FUNC
    );
    static final FunctionDescriptor io_uring_cqe_seen$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle io_uring_cqe_seen$MH = RuntimeHelper.downcallHandle(
        "io_uring_cqe_seen",
        constants$22.io_uring_cqe_seen$FUNC
    );
}


