// Generated by jextract

package top.dreamlike.liburing;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
 class liburing_h_1 {

    public static MemorySegment PRIdLEAST16() {
        return constants$28.PRIdLEAST16$SEGMENT;
    }
    public static MemorySegment PRIdLEAST32() {
        return constants$28.PRIdLEAST32$SEGMENT;
    }
    public static MemorySegment PRIdLEAST64() {
        return constants$28.PRIdLEAST64$SEGMENT;
    }
    public static MemorySegment PRIdFAST8() {
        return constants$29.PRIdFAST8$SEGMENT;
    }
    public static MemorySegment PRIdFAST16() {
        return constants$29.PRIdFAST16$SEGMENT;
    }
    public static MemorySegment PRIdFAST32() {
        return constants$29.PRIdFAST32$SEGMENT;
    }
    public static MemorySegment PRIdFAST64() {
        return constants$29.PRIdFAST64$SEGMENT;
    }
    public static MemorySegment PRIi8() {
        return constants$29.PRIi8$SEGMENT;
    }
    public static MemorySegment PRIi16() {
        return constants$29.PRIi16$SEGMENT;
    }
    public static MemorySegment PRIi32() {
        return constants$30.PRIi32$SEGMENT;
    }
    public static MemorySegment PRIi64() {
        return constants$30.PRIi64$SEGMENT;
    }
    public static MemorySegment PRIiLEAST8() {
        return constants$30.PRIiLEAST8$SEGMENT;
    }
    public static MemorySegment PRIiLEAST16() {
        return constants$30.PRIiLEAST16$SEGMENT;
    }
    public static MemorySegment PRIiLEAST32() {
        return constants$30.PRIiLEAST32$SEGMENT;
    }
    public static MemorySegment PRIiLEAST64() {
        return constants$30.PRIiLEAST64$SEGMENT;
    }
    public static MemorySegment PRIiFAST8() {
        return constants$31.PRIiFAST8$SEGMENT;
    }
    public static MemorySegment PRIiFAST16() {
        return constants$31.PRIiFAST16$SEGMENT;
    }
    public static MemorySegment PRIiFAST32() {
        return constants$31.PRIiFAST32$SEGMENT;
    }
    public static MemorySegment PRIiFAST64() {
        return constants$31.PRIiFAST64$SEGMENT;
    }
    public static MemorySegment PRIo8() {
        return constants$31.PRIo8$SEGMENT;
    }
    public static MemorySegment PRIo16() {
        return constants$31.PRIo16$SEGMENT;
    }
    public static MemorySegment PRIo32() {
        return constants$32.PRIo32$SEGMENT;
    }
    public static MemorySegment PRIo64() {
        return constants$32.PRIo64$SEGMENT;
    }
    public static MemorySegment PRIoLEAST8() {
        return constants$32.PRIoLEAST8$SEGMENT;
    }
    public static MemorySegment PRIoLEAST16() {
        return constants$32.PRIoLEAST16$SEGMENT;
    }
    public static MemorySegment PRIoLEAST32() {
        return constants$32.PRIoLEAST32$SEGMENT;
    }
    public static MemorySegment PRIoLEAST64() {
        return constants$32.PRIoLEAST64$SEGMENT;
    }
    public static MemorySegment PRIoFAST8() {
        return constants$33.PRIoFAST8$SEGMENT;
    }
    public static MemorySegment PRIoFAST16() {
        return constants$33.PRIoFAST16$SEGMENT;
    }
    public static MemorySegment PRIoFAST32() {
        return constants$33.PRIoFAST32$SEGMENT;
    }
    public static MemorySegment PRIoFAST64() {
        return constants$33.PRIoFAST64$SEGMENT;
    }
    public static MemorySegment PRIu8() {
        return constants$33.PRIu8$SEGMENT;
    }
    public static MemorySegment PRIu16() {
        return constants$33.PRIu16$SEGMENT;
    }
    public static MemorySegment PRIu32() {
        return constants$34.PRIu32$SEGMENT;
    }
    public static MemorySegment PRIu64() {
        return constants$34.PRIu64$SEGMENT;
    }
    public static MemorySegment PRIuLEAST8() {
        return constants$34.PRIuLEAST8$SEGMENT;
    }
    public static MemorySegment PRIuLEAST16() {
        return constants$34.PRIuLEAST16$SEGMENT;
    }
    public static MemorySegment PRIuLEAST32() {
        return constants$34.PRIuLEAST32$SEGMENT;
    }
    public static MemorySegment PRIuLEAST64() {
        return constants$34.PRIuLEAST64$SEGMENT;
    }
    public static MemorySegment PRIuFAST8() {
        return constants$35.PRIuFAST8$SEGMENT;
    }
    public static MemorySegment PRIuFAST16() {
        return constants$35.PRIuFAST16$SEGMENT;
    }
    public static MemorySegment PRIuFAST32() {
        return constants$35.PRIuFAST32$SEGMENT;
    }
    public static MemorySegment PRIuFAST64() {
        return constants$35.PRIuFAST64$SEGMENT;
    }
    public static MemorySegment PRIx8() {
        return constants$35.PRIx8$SEGMENT;
    }
    public static MemorySegment PRIx16() {
        return constants$35.PRIx16$SEGMENT;
    }
    public static MemorySegment PRIx32() {
        return constants$36.PRIx32$SEGMENT;
    }
    public static MemorySegment PRIx64() {
        return constants$36.PRIx64$SEGMENT;
    }
    public static MemorySegment PRIxLEAST8() {
        return constants$36.PRIxLEAST8$SEGMENT;
    }
    public static MemorySegment PRIxLEAST16() {
        return constants$36.PRIxLEAST16$SEGMENT;
    }
    public static MemorySegment PRIxLEAST32() {
        return constants$36.PRIxLEAST32$SEGMENT;
    }
    public static MemorySegment PRIxLEAST64() {
        return constants$36.PRIxLEAST64$SEGMENT;
    }
    public static MemorySegment PRIxFAST8() {
        return constants$37.PRIxFAST8$SEGMENT;
    }
    public static MemorySegment PRIxFAST16() {
        return constants$37.PRIxFAST16$SEGMENT;
    }
    public static MemorySegment PRIxFAST32() {
        return constants$37.PRIxFAST32$SEGMENT;
    }
    public static MemorySegment PRIxFAST64() {
        return constants$37.PRIxFAST64$SEGMENT;
    }
    public static MemorySegment PRIX8() {
        return constants$37.PRIX8$SEGMENT;
    }
    public static MemorySegment PRIX16() {
        return constants$37.PRIX16$SEGMENT;
    }
    public static MemorySegment PRIX32() {
        return constants$38.PRIX32$SEGMENT;
    }
    public static MemorySegment PRIX64() {
        return constants$38.PRIX64$SEGMENT;
    }
    public static MemorySegment PRIXLEAST8() {
        return constants$38.PRIXLEAST8$SEGMENT;
    }
    public static MemorySegment PRIXLEAST16() {
        return constants$38.PRIXLEAST16$SEGMENT;
    }
    public static MemorySegment PRIXLEAST32() {
        return constants$38.PRIXLEAST32$SEGMENT;
    }
    public static MemorySegment PRIXLEAST64() {
        return constants$38.PRIXLEAST64$SEGMENT;
    }
    public static MemorySegment PRIXFAST8() {
        return constants$39.PRIXFAST8$SEGMENT;
    }
    public static MemorySegment PRIXFAST16() {
        return constants$39.PRIXFAST16$SEGMENT;
    }
    public static MemorySegment PRIXFAST32() {
        return constants$39.PRIXFAST32$SEGMENT;
    }
    public static MemorySegment PRIXFAST64() {
        return constants$39.PRIXFAST64$SEGMENT;
    }
    public static MemorySegment PRIdMAX() {
        return constants$39.PRIdMAX$SEGMENT;
    }
    public static MemorySegment PRIiMAX() {
        return constants$39.PRIiMAX$SEGMENT;
    }
    public static MemorySegment PRIoMAX() {
        return constants$40.PRIoMAX$SEGMENT;
    }
    public static MemorySegment PRIuMAX() {
        return constants$40.PRIuMAX$SEGMENT;
    }
    public static MemorySegment PRIxMAX() {
        return constants$40.PRIxMAX$SEGMENT;
    }
    public static MemorySegment PRIXMAX() {
        return constants$40.PRIXMAX$SEGMENT;
    }
    public static MemorySegment PRIdPTR() {
        return constants$40.PRIdPTR$SEGMENT;
    }
    public static MemorySegment PRIiPTR() {
        return constants$40.PRIiPTR$SEGMENT;
    }
    public static MemorySegment PRIoPTR() {
        return constants$41.PRIoPTR$SEGMENT;
    }
    public static MemorySegment PRIuPTR() {
        return constants$41.PRIuPTR$SEGMENT;
    }
    public static MemorySegment PRIxPTR() {
        return constants$41.PRIxPTR$SEGMENT;
    }
    public static MemorySegment PRIXPTR() {
        return constants$41.PRIXPTR$SEGMENT;
    }
    public static MemorySegment SCNd8() {
        return constants$41.SCNd8$SEGMENT;
    }
    public static MemorySegment SCNd16() {
        return constants$41.SCNd16$SEGMENT;
    }
    public static MemorySegment SCNd32() {
        return constants$42.SCNd32$SEGMENT;
    }
    public static MemorySegment SCNd64() {
        return constants$42.SCNd64$SEGMENT;
    }
    public static MemorySegment SCNdLEAST8() {
        return constants$42.SCNdLEAST8$SEGMENT;
    }
    public static MemorySegment SCNdLEAST16() {
        return constants$42.SCNdLEAST16$SEGMENT;
    }
    public static MemorySegment SCNdLEAST32() {
        return constants$42.SCNdLEAST32$SEGMENT;
    }
    public static MemorySegment SCNdLEAST64() {
        return constants$42.SCNdLEAST64$SEGMENT;
    }
    public static MemorySegment SCNdFAST8() {
        return constants$43.SCNdFAST8$SEGMENT;
    }
    public static MemorySegment SCNdFAST16() {
        return constants$43.SCNdFAST16$SEGMENT;
    }
    public static MemorySegment SCNdFAST32() {
        return constants$43.SCNdFAST32$SEGMENT;
    }
    public static MemorySegment SCNdFAST64() {
        return constants$43.SCNdFAST64$SEGMENT;
    }
    public static MemorySegment SCNi8() {
        return constants$43.SCNi8$SEGMENT;
    }
    public static MemorySegment SCNi16() {
        return constants$43.SCNi16$SEGMENT;
    }
    public static MemorySegment SCNi32() {
        return constants$44.SCNi32$SEGMENT;
    }
    public static MemorySegment SCNi64() {
        return constants$44.SCNi64$SEGMENT;
    }
    public static MemorySegment SCNiLEAST8() {
        return constants$44.SCNiLEAST8$SEGMENT;
    }
    public static MemorySegment SCNiLEAST16() {
        return constants$44.SCNiLEAST16$SEGMENT;
    }
    public static MemorySegment SCNiLEAST32() {
        return constants$44.SCNiLEAST32$SEGMENT;
    }
    public static MemorySegment SCNiLEAST64() {
        return constants$44.SCNiLEAST64$SEGMENT;
    }
    public static MemorySegment SCNiFAST8() {
        return constants$45.SCNiFAST8$SEGMENT;
    }
    public static MemorySegment SCNiFAST16() {
        return constants$45.SCNiFAST16$SEGMENT;
    }
    public static MemorySegment SCNiFAST32() {
        return constants$45.SCNiFAST32$SEGMENT;
    }
    public static MemorySegment SCNiFAST64() {
        return constants$45.SCNiFAST64$SEGMENT;
    }
    public static MemorySegment SCNu8() {
        return constants$45.SCNu8$SEGMENT;
    }
    public static MemorySegment SCNu16() {
        return constants$45.SCNu16$SEGMENT;
    }
    public static MemorySegment SCNu32() {
        return constants$46.SCNu32$SEGMENT;
    }
    public static MemorySegment SCNu64() {
        return constants$46.SCNu64$SEGMENT;
    }
    public static MemorySegment SCNuLEAST8() {
        return constants$46.SCNuLEAST8$SEGMENT;
    }
    public static MemorySegment SCNuLEAST16() {
        return constants$46.SCNuLEAST16$SEGMENT;
    }
    public static MemorySegment SCNuLEAST32() {
        return constants$46.SCNuLEAST32$SEGMENT;
    }
    public static MemorySegment SCNuLEAST64() {
        return constants$46.SCNuLEAST64$SEGMENT;
    }
    public static MemorySegment SCNuFAST8() {
        return constants$47.SCNuFAST8$SEGMENT;
    }
    public static MemorySegment SCNuFAST16() {
        return constants$47.SCNuFAST16$SEGMENT;
    }
    public static MemorySegment SCNuFAST32() {
        return constants$47.SCNuFAST32$SEGMENT;
    }
    public static MemorySegment SCNuFAST64() {
        return constants$47.SCNuFAST64$SEGMENT;
    }
    public static MemorySegment SCNo8() {
        return constants$47.SCNo8$SEGMENT;
    }
    public static MemorySegment SCNo16() {
        return constants$47.SCNo16$SEGMENT;
    }
    public static MemorySegment SCNo32() {
        return constants$48.SCNo32$SEGMENT;
    }
    public static MemorySegment SCNo64() {
        return constants$48.SCNo64$SEGMENT;
    }
    public static MemorySegment SCNoLEAST8() {
        return constants$48.SCNoLEAST8$SEGMENT;
    }
    public static MemorySegment SCNoLEAST16() {
        return constants$48.SCNoLEAST16$SEGMENT;
    }
    public static MemorySegment SCNoLEAST32() {
        return constants$48.SCNoLEAST32$SEGMENT;
    }
    public static MemorySegment SCNoLEAST64() {
        return constants$48.SCNoLEAST64$SEGMENT;
    }
    public static MemorySegment SCNoFAST8() {
        return constants$49.SCNoFAST8$SEGMENT;
    }
    public static MemorySegment SCNoFAST16() {
        return constants$49.SCNoFAST16$SEGMENT;
    }
    public static MemorySegment SCNoFAST32() {
        return constants$49.SCNoFAST32$SEGMENT;
    }
    public static MemorySegment SCNoFAST64() {
        return constants$49.SCNoFAST64$SEGMENT;
    }
    public static MemorySegment SCNx8() {
        return constants$49.SCNx8$SEGMENT;
    }
    public static MemorySegment SCNx16() {
        return constants$49.SCNx16$SEGMENT;
    }
    public static MemorySegment SCNx32() {
        return constants$50.SCNx32$SEGMENT;
    }
    public static MemorySegment SCNx64() {
        return constants$50.SCNx64$SEGMENT;
    }
    public static MemorySegment SCNxLEAST8() {
        return constants$50.SCNxLEAST8$SEGMENT;
    }
    public static MemorySegment SCNxLEAST16() {
        return constants$50.SCNxLEAST16$SEGMENT;
    }
    public static MemorySegment SCNxLEAST32() {
        return constants$50.SCNxLEAST32$SEGMENT;
    }
    public static MemorySegment SCNxLEAST64() {
        return constants$50.SCNxLEAST64$SEGMENT;
    }
    public static MemorySegment SCNxFAST8() {
        return constants$51.SCNxFAST8$SEGMENT;
    }
    public static MemorySegment SCNxFAST16() {
        return constants$51.SCNxFAST16$SEGMENT;
    }
    public static MemorySegment SCNxFAST32() {
        return constants$51.SCNxFAST32$SEGMENT;
    }
    public static MemorySegment SCNxFAST64() {
        return constants$51.SCNxFAST64$SEGMENT;
    }
    public static MemorySegment SCNdMAX() {
        return constants$51.SCNdMAX$SEGMENT;
    }
    public static MemorySegment SCNiMAX() {
        return constants$51.SCNiMAX$SEGMENT;
    }
    public static MemorySegment SCNoMAX() {
        return constants$52.SCNoMAX$SEGMENT;
    }
    public static MemorySegment SCNuMAX() {
        return constants$52.SCNuMAX$SEGMENT;
    }
    public static MemorySegment SCNxMAX() {
        return constants$52.SCNxMAX$SEGMENT;
    }
    public static MemorySegment SCNdPTR() {
        return constants$52.SCNdPTR$SEGMENT;
    }
    public static MemorySegment SCNiPTR() {
        return constants$52.SCNiPTR$SEGMENT;
    }
    public static MemorySegment SCNoPTR() {
        return constants$52.SCNoPTR$SEGMENT;
    }
    public static MemorySegment SCNuPTR() {
        return constants$53.SCNuPTR$SEGMENT;
    }
    public static MemorySegment SCNxPTR() {
        return constants$53.SCNxPTR$SEGMENT;
    }
    public static MemoryAddress NULL() {
        return constants$53.NULL$ADDR;
    }
    public static long CLOCKS_PER_SEC() {
        return 1000000L;
    }
    public static int _IOC_NRMASK() {
        return (int)255L;
    }
    public static int _IOC_TYPEMASK() {
        return (int)255L;
    }
    public static int _IOC_SIZEMASK() {
        return (int)16383L;
    }
    public static int _IOC_DIRMASK() {
        return (int)3L;
    }
    public static int _IOC_TYPESHIFT() {
        return (int)8L;
    }
    public static int _IOC_SIZESHIFT() {
        return (int)16L;
    }
    public static int _IOC_DIRSHIFT() {
        return (int)30L;
    }
    public static int _IOC_NONE() {
        return (int)0L;
    }
    public static int _IOC_WRITE() {
        return (int)1L;
    }
    public static int _IOC_READ() {
        return (int)2L;
    }
    public static int IOC_IN() {
        return (int)1073741824L;
    }
    public static int IOC_OUT() {
        return (int)2147483648L;
    }
    public static int IOC_INOUT() {
        return (int)3221225472L;
    }
    public static int IOCSIZE_MASK() {
        return (int)1073676288L;
    }
    public static int IOCSIZE_SHIFT() {
        return (int)16L;
    }
    public static MemorySegment FSCRYPT_KEY_DESC_PREFIX() {
        return constants$53.FSCRYPT_KEY_DESC_PREFIX$SEGMENT;
    }
    public static long FS_IOC_SET_ENCRYPTION_POLICY() {
        return 2148296211L;
    }
    public static long FS_IOC_GET_ENCRYPTION_PWSALT() {
        return 1074816532L;
    }
    public static long FS_IOC_GET_ENCRYPTION_POLICY() {
        return 1074554389L;
    }
    public static long FS_IOC_GET_ENCRYPTION_POLICY_EX() {
        return 3221841430L;
    }
    public static long FS_IOC_ADD_ENCRYPTION_KEY() {
        return 3226494487L;
    }
    public static long FS_IOC_REMOVE_ENCRYPTION_KEY() {
        return 3225445912L;
    }
    public static long FS_IOC_REMOVE_ENCRYPTION_KEY_ALL_USERS() {
        return 3225445913L;
    }
    public static long FS_IOC_GET_ENCRYPTION_KEY_STATUS() {
        return 3229640218L;
    }
    public static int FS_KEY_DESCRIPTOR_SIZE() {
        return (int)8L;
    }
    public static int FS_POLICY_FLAGS_PAD_4() {
        return (int)0L;
    }
    public static int FS_POLICY_FLAGS_PAD_8() {
        return (int)1L;
    }
    public static int FS_POLICY_FLAGS_PAD_16() {
        return (int)2L;
    }
    public static int FS_POLICY_FLAGS_PAD_32() {
        return (int)3L;
    }
    public static int FS_POLICY_FLAGS_PAD_MASK() {
        return (int)3L;
    }
    public static int FS_POLICY_FLAG_DIRECT_KEY() {
        return (int)4L;
    }
    public static int FS_ENCRYPTION_MODE_AES_256_XTS() {
        return (int)1L;
    }
    public static int FS_ENCRYPTION_MODE_AES_256_CTS() {
        return (int)4L;
    }
    public static int FS_ENCRYPTION_MODE_AES_128_CBC() {
        return (int)5L;
    }
    public static int FS_ENCRYPTION_MODE_AES_128_CTS() {
        return (int)6L;
    }
    public static int FS_ENCRYPTION_MODE_ADIANTUM() {
        return (int)9L;
    }
    public static MemorySegment FS_KEY_DESC_PREFIX() {
        return constants$53.FS_KEY_DESC_PREFIX$SEGMENT;
    }
    public static int FS_KEY_DESC_PREFIX_SIZE() {
        return (int)8L;
    }
    public static int FS_MAX_KEY_SIZE() {
        return (int)64L;
    }
    public static int MS_POSIXACL() {
        return (int)65536L;
    }
    public static int MS_UNBINDABLE() {
        return (int)131072L;
    }
    public static int MS_PRIVATE() {
        return (int)262144L;
    }
    public static int MS_SLAVE() {
        return (int)524288L;
    }
    public static int MS_SHARED() {
        return (int)1048576L;
    }
    public static int MS_RELATIME() {
        return (int)2097152L;
    }
    public static int MS_KERNMOUNT() {
        return (int)4194304L;
    }
    public static int MS_I_VERSION() {
        return (int)8388608L;
    }
    public static int MS_STRICTATIME() {
        return (int)16777216L;
    }
    public static int MS_LAZYTIME() {
        return (int)33554432L;
    }
    public static int MS_SUBMOUNT() {
        return (int)67108864L;
    }
    public static int MS_NOREMOTELOCK() {
        return (int)134217728L;
    }
    public static int MS_NOSEC() {
        return (int)268435456L;
    }
    public static int MS_BORN() {
        return (int)536870912L;
    }
    public static int MS_ACTIVE() {
        return (int)1073741824L;
    }
    public static int MS_NOUSER() {
        return (int)-2147483648L;
    }
    public static int MS_RMT_MASK() {
        return (int)41943121L;
    }
    public static int MS_MGC_VAL() {
        return (int)3236757504L;
    }
    public static int MS_MGC_MSK() {
        return (int)4294901760L;
    }
    public static int BLOCK_SIZE() {
        return (int)1024L;
    }
    public static int SEEK_MAX() {
        return (int)4L;
    }
    public static int RENAME_NOREPLACE() {
        return (int)1L;
    }
    public static int RENAME_EXCHANGE() {
        return (int)2L;
    }
    public static int RENAME_WHITEOUT() {
        return (int)4L;
    }
    public static int FS_XFLAG_HASATTR() {
        return (int)2147483648L;
    }
    public static int BLKROSET() {
        return (int)4701L;
    }
    public static int BLKROGET() {
        return (int)4702L;
    }
    public static int BLKRRPART() {
        return (int)4703L;
    }
    public static int BLKGETSIZE() {
        return (int)4704L;
    }
    public static int BLKFLSBUF() {
        return (int)4705L;
    }
    public static int BLKRASET() {
        return (int)4706L;
    }
    public static int BLKRAGET() {
        return (int)4707L;
    }
    public static int BLKFRASET() {
        return (int)4708L;
    }
    public static int BLKFRAGET() {
        return (int)4709L;
    }
    public static int BLKSECTSET() {
        return (int)4710L;
    }
    public static int BLKSECTGET() {
        return (int)4711L;
    }
    public static int BLKSSZGET() {
        return (int)4712L;
    }
    public static long BLKBSZGET() {
        return 2148012656L;
    }
    public static long BLKBSZSET() {
        return 1074270833L;
    }
    public static long BLKGETSIZE64() {
        return 2148012658L;
    }
    public static int BLKTRACESTART() {
        return (int)4724L;
    }
    public static int BLKTRACESTOP() {
        return (int)4725L;
    }
    public static int BLKTRACETEARDOWN() {
        return (int)4726L;
    }
    public static int BLKDISCARD() {
        return (int)4727L;
    }
    public static int BLKIOMIN() {
        return (int)4728L;
    }
    public static int BLKIOOPT() {
        return (int)4729L;
    }
    public static int BLKALIGNOFF() {
        return (int)4730L;
    }
    public static int BLKPBSZGET() {
        return (int)4731L;
    }
    public static int BLKDISCARDZEROES() {
        return (int)4732L;
    }
    public static int BLKSECDISCARD() {
        return (int)4733L;
    }
    public static int BLKROTATIONAL() {
        return (int)4734L;
    }
    public static int BLKZEROOUT() {
        return (int)4735L;
    }
    public static int FIBMAP() {
        return (int)1L;
    }
    public static int FIGETBSZ() {
        return (int)2L;
    }
    public static long FIFREEZE() {
        return 3221510263L;
    }
    public static long FITHAW() {
        return 3221510264L;
    }
    public static long FITRIM() {
        return 3222820985L;
    }
    public static long FICLONE() {
        return 1074041865L;
    }
    public static long FICLONERANGE() {
        return 1075876877L;
    }
    public static long FIDEDUPERANGE() {
        return 3222836278L;
    }
    public static long FS_IOC_GETFLAGS() {
        return 2148034049L;
    }
    public static long FS_IOC_SETFLAGS() {
        return 1074292226L;
    }
    public static long FS_IOC_GETVERSION() {
        return 2148038145L;
    }
    public static long FS_IOC_SETVERSION() {
        return 1074296322L;
    }
    public static long FS_IOC32_GETFLAGS() {
        return 2147771905L;
    }
    public static long FS_IOC32_SETFLAGS() {
        return 1074030082L;
    }
    public static long FS_IOC32_GETVERSION() {
        return 2147776001L;
    }
    public static long FS_IOC32_SETVERSION() {
        return 1074034178L;
    }
    public static long FS_IOC_FSGETXATTR() {
        return 2149341215L;
    }
    public static long FS_IOC_FSSETXATTR() {
        return 1075599392L;
    }
    public static long FS_IOC_GETFSLABEL() {
        return 2164298801L;
    }
    public static long FS_IOC_SETFSLABEL() {
        return 1090556978L;
    }
    public static int FS_RESERVED_FL() {
        return (int)2147483648L;
    }
    public static int SYNC_FILE_RANGE_WRITE_AND_WAIT() {
        return (int)7L;
    }
    public static int RWF_HIPRI() {
        return (int)1L;
    }
    public static int RWF_DSYNC() {
        return (int)2L;
    }
    public static int RWF_SYNC() {
        return (int)4L;
    }
    public static int RWF_NOWAIT() {
        return (int)8L;
    }
    public static int RWF_APPEND() {
        return (int)16L;
    }
    public static int RWF_SUPPORTED() {
        return (int)31L;
    }
    public static int IOSQE_FIXED_FILE() {
        return (int)1L;
    }
    public static int IOSQE_IO_DRAIN() {
        return (int)2L;
    }
    public static int IOSQE_IO_LINK() {
        return (int)4L;
    }
    public static int IORING_SETUP_IOPOLL() {
        return (int)1L;
    }
    public static int IORING_SETUP_SQPOLL() {
        return (int)2L;
    }
    public static int IORING_SETUP_SQ_AFF() {
        return (int)4L;
    }
    public static int IORING_SETUP_CQSIZE() {
        return (int)8L;
    }
    public static int IORING_FSYNC_DATASYNC() {
        return (int)1L;
    }
    public static int IORING_TIMEOUT_ABS() {
        return (int)1L;
    }
    public static long IORING_OFF_SQ_RING() {
        return 0L;
    }
    public static long IORING_OFF_CQ_RING() {
        return 134217728L;
    }
    public static long IORING_OFF_SQES() {
        return 268435456L;
    }
    public static int IORING_SQ_NEED_WAKEUP() {
        return (int)1L;
    }
    public static int IORING_ENTER_GETEVENTS() {
        return (int)1L;
    }
    public static int IORING_ENTER_SQ_WAKEUP() {
        return (int)2L;
    }
    public static int IORING_FEAT_SINGLE_MMAP() {
        return (int)1L;
    }
    public static long LIBURING_UDATA_TIMEOUT() {
        return -1L;
    }
}


