// Generated by jextract

package top.dreamlike.nativeLib.liburing;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;

class constants$28 {

    static final FunctionDescriptor io_uring_sqe_set_data$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle io_uring_sqe_set_data$MH = RuntimeHelper.downcallHandle(
        "io_uring_sqe_set_data",
        constants$28.io_uring_sqe_set_data$FUNC
    );
    static final FunctionDescriptor io_uring_cqe_get_data$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle io_uring_cqe_get_data$MH = RuntimeHelper.downcallHandle(
        "io_uring_cqe_get_data",
        constants$28.io_uring_cqe_get_data$FUNC
    );
    static final FunctionDescriptor io_uring_sqe_set_flags$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle io_uring_sqe_set_flags$MH = RuntimeHelper.downcallHandle(
        "io_uring_sqe_set_flags",
        constants$28.io_uring_sqe_set_flags$FUNC
    );
    static final FunctionDescriptor io_uring_prep_rw$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle io_uring_prep_rw$MH = RuntimeHelper.downcallHandle(
        "io_uring_prep_rw",
        constants$28.io_uring_prep_rw$FUNC
    );
    static final FunctionDescriptor io_uring_prep_splice$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle io_uring_prep_splice$MH = RuntimeHelper.downcallHandle(
        "io_uring_prep_splice",
        constants$28.io_uring_prep_splice$FUNC
    );
    static final FunctionDescriptor io_uring_prep_tee$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle io_uring_prep_tee$MH = RuntimeHelper.downcallHandle(
        "io_uring_prep_tee",
        constants$28.io_uring_prep_tee$FUNC
    );
}


