// Generated by jextract

package top.dreamlike.nativeLib.liburing;

import java.lang.invoke.VarHandle;
import java.lang.foreign.*;

public class ucontext_t {

    static final  GroupLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_LONG_LONG$LAYOUT.withName("__uc_flags"),
        Constants$root.C_POINTER$LAYOUT.withName("uc_link"),
        MemoryLayout.structLayout(
            Constants$root.C_POINTER$LAYOUT.withName("ss_sp"),
            Constants$root.C_INT$LAYOUT.withName("ss_flags"),
            MemoryLayout.paddingLayout(32),
            Constants$root.C_LONG_LONG$LAYOUT.withName("ss_size")
        ).withName("uc_stack"),
        MemoryLayout.structLayout(
            MemoryLayout.sequenceLayout(23, Constants$root.C_LONG_LONG$LAYOUT).withName("__gregs"),
            Constants$root.C_POINTER$LAYOUT.withName("__fpregs"),
            MemoryLayout.sequenceLayout(8, Constants$root.C_LONG_LONG$LAYOUT).withName("__reserved1")
        ).withName("uc_mcontext"),
        MemoryLayout.structLayout(
            MemoryLayout.sequenceLayout(16, Constants$root.C_LONG_LONG$LAYOUT).withName("__val")
        ).withName("uc_sigmask"),
        MemoryLayout.structLayout(
            Constants$root.C_SHORT$LAYOUT.withName("__cwd"),
            Constants$root.C_SHORT$LAYOUT.withName("__swd"),
            Constants$root.C_SHORT$LAYOUT.withName("__ftw"),
            Constants$root.C_SHORT$LAYOUT.withName("__fop"),
            Constants$root.C_LONG_LONG$LAYOUT.withName("__rip"),
            Constants$root.C_LONG_LONG$LAYOUT.withName("__rdp"),
            Constants$root.C_INT$LAYOUT.withName("__mxcsr"),
            Constants$root.C_INT$LAYOUT.withName("__mxcr_mask"),
            MemoryLayout.sequenceLayout(8, MemoryLayout.structLayout(
                MemoryLayout.sequenceLayout(4, Constants$root.C_SHORT$LAYOUT).withName("__significand"),
                Constants$root.C_SHORT$LAYOUT.withName("__exponent"),
                MemoryLayout.sequenceLayout(3, Constants$root.C_SHORT$LAYOUT).withName("__glibc_reserved1")
            ).withName("_libc_fpxreg")).withName("_st"),
            MemoryLayout.sequenceLayout(16, MemoryLayout.structLayout(
                MemoryLayout.sequenceLayout(4, Constants$root.C_INT$LAYOUT).withName("__element")
            ).withName("_libc_xmmreg")).withName("_xmm"),
            MemoryLayout.sequenceLayout(24, Constants$root.C_INT$LAYOUT).withName("__glibc_reserved1")
        ).withName("__fpregs_mem"),
        MemoryLayout.sequenceLayout(4, Constants$root.C_LONG_LONG$LAYOUT).withName("__ssp")
    ).withName("ucontext_t");
    public static MemoryLayout $LAYOUT() {
        return ucontext_t.$struct$LAYOUT;
    }
    static final VarHandle __uc_flags$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("__uc_flags"));
    public static VarHandle __uc_flags$VH() {
        return ucontext_t.__uc_flags$VH;
    }
    public static long __uc_flags$get(MemorySegment seg) {
        return (long)ucontext_t.__uc_flags$VH.get(seg);
    }
    public static void __uc_flags$set( MemorySegment seg, long x) {
        ucontext_t.__uc_flags$VH.set(seg, x);
    }
    public static long __uc_flags$get(MemorySegment seg, long index) {
        return (long)ucontext_t.__uc_flags$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void __uc_flags$set(MemorySegment seg, long index, long x) {
        ucontext_t.__uc_flags$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle uc_link$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("uc_link"));
    public static VarHandle uc_link$VH() {
        return ucontext_t.uc_link$VH;
    }
    public static MemoryAddress uc_link$get(MemorySegment seg) {
        return (java.lang.foreign.MemoryAddress)ucontext_t.uc_link$VH.get(seg);
    }
    public static void uc_link$set( MemorySegment seg, MemoryAddress x) {
        ucontext_t.uc_link$VH.set(seg, x);
    }
    public static MemoryAddress uc_link$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemoryAddress)ucontext_t.uc_link$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void uc_link$set(MemorySegment seg, long index, MemoryAddress x) {
        ucontext_t.uc_link$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static MemorySegment uc_stack$slice(MemorySegment seg) {
        return seg.asSlice(16, 24);
    }
    public static MemorySegment uc_mcontext$slice(MemorySegment seg) {
        return seg.asSlice(40, 256);
    }
    public static MemorySegment uc_sigmask$slice(MemorySegment seg) {
        return seg.asSlice(296, 128);
    }
    public static MemorySegment __fpregs_mem$slice(MemorySegment seg) {
        return seg.asSlice(424, 512);
    }
    public static MemorySegment __ssp$slice(MemorySegment seg) {
        return seg.asSlice(936, 32);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, MemorySession session) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, session); }
}


