// Generated by jextract

package top.dreamlike.nativeLib.mman;

import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.MemoryAddress;
import java.lang.invoke.MethodHandle;

class constants$2 {

    static final FunctionDescriptor shm_unlink$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
            Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle shm_unlink$MH = RuntimeHelper.downcallHandle(
            "shm_unlink",
            constants$2.shm_unlink$FUNC
    );
    static final MemoryAddress MAP_FAILED$ADDR = MemoryAddress.ofLong(-1L);
}


