// Generated by jextract

package top.dreamlike.nativeLib.mman;

import top.dreamlike.common.CType;
import top.dreamlike.helper.RuntimeHelper;

import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;
class constants$2 {

    static final FunctionDescriptor shm_unlink$FUNC = FunctionDescriptor.of(CType.C_INT$LAYOUT,
            CType.C_POINTER$LAYOUT
    );
    static final MethodHandle shm_unlink$MH = RuntimeHelper.downcallHandle(
            "shm_unlink",
            constants$2.shm_unlink$FUNC
    );
    static final MemorySegment MAP_FAILED$ADDR = MemorySegment.ofAddress(-1L);
}


